version: '2'

services:
  app:
    image: 'docker-4clients:latest'
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: 4Clients
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:test
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - DB_URL=jdbc:h2:mem:test
      - DB_USER=test
      - DB_PASSWORD=test