version: '3'

services:
  mongo:
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=clients
    image: mongo
    networks:
      - mongo-net

  localRabbitMQ:
    image: rabbitmq:3.11.13
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mongo-net

  auth-service:
    build: ./auth-service
    ports:
      - "8090:8090"
    container_name: auth-service
    environment:
      - spring.data.mongodb.uri=mongodb://mongo:27017/clients
      - spring_rabbitmq_host=localRabbitMQ
    links:
      - localRabbitMQ
      - mongo
    networks:
      - mongo-net
    depends_on:
      - mongo
      - localRabbitMQ

  management-service:
    build: ./management-service
    ports:
      - "8091:8091"
    container_name: management-service
    environment:
      - spring.data.mongodb.uri=mongodb://mongo:27017/clients
      - spring_rabbitmq_host=localRabbitMQ
    links:
      - localRabbitMQ
      - mongo
    networks:
      - mongo-net
    depends_on:
      - mongo
      - localRabbitMQ

  telegram-service:
    build: ./telegram-service
    ports:
      - "8093:8093"
    container_name: telegram-service
    environment:
      - spring_rabbitmq_host=localRabbitMQ
    links:
      - localRabbitMQ
    networks:
      - mongo-net
    depends_on:
      - localRabbitMQ

  client-service:
    build: ./client-service
    ports:
      - "8092:8092"
    container_name: client-service
    environment:
      - spring.data.mongodb.uri=mongodb://mongo:27017/clients
      - spring_rabbitmq_host=localRabbitMQ
    links:
      - mongo
      - localRabbitMQ
    networks:
      - mongo-net
    depends_on:
      - mongo
      - localRabbitMQ

networks:
  mongo-net:
    driver: bridge