version: '3'

services:
  mongo:
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=clients
    image: mongo
    networks:
      - mongo-net

  localRabbitMQ:
    image: rabbitmq:3.11.13
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mongo-net

  auth-service:
    build: ./auth-service
    ports:
      - "8080:8080"
    container_name: auth-service
    environment:
      - spring.data.mongodb.uri=mongodb://mongo:27017/clients
      - spring_rabbitmq_host=localRabbitMQ
    links:
      - "localRabbitMQ"
      - mongo
    networks:
      - mongo-net

  management-service:
    build: ./management-service
    ports:
      - "8081:8081"
    container_name: management-service
    environment:
      - spring.data.mongodb.uri=mongodb://mongo:27017/clients
      - spring_rabbitmq_host=localRabbitMQ
    links:
      - "localRabbitMQ"
      - mongo
    networks:
      - mongo-net

  client-service:
    build: ./client-service
    ports:
      - "8082:8082"
    container_name: client-service
    environment:
      - spring.data.mongodb.uri=mongodb://mongo:27017/clients
    links:
      - mongo
    networks:
      - mongo-net

networks:
  mongo-net:
    driver: bridge